### ISSUE TITLE
undefined method `foreign_keys' for #<ActiveRecord::ConnectionAdapters::OracleEnhanced::TableDefinition

### ISSUE THREAD

**Issue by akil-rails** [rsim/oracle-enhanced#651]
A pretty standard migration is giving an error - I suppose it is linked to a recent pull. 

```ruby
class CreateEcolUnapprovedRecords < ActiveRecord::Migration
  def change
    create_table :ecol_unapproved_records do |t|
      t.integer :ecol_approvable_id
      t.string :ecol_approvable_type

      t.timestamps null: false
    end
  end
end
```

Commenting out the lines , makes it work ..
```ruby
          #td.foreign_keys.each_pair do |other_table_name, foreign_key_options|
          #  p other_table_name
          #  add_foreign_key(table_name, other_table_name, foreign_key_options)
          #end
```

```ruby
StandardError: An error has occurred, all later migrations canceled:

undefined method `foreign_keys' for #<ActiveRecord::ConnectionAdapters::OracleEnhanced::TableDefinition:0x007fcb9b534670>/Users/akhileshkataria/Code/service_center/vendor/bundle/bundler/gems/oracle-enhanced-4eb68ac7acb6/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb:93:in `create_table'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/Users/akhileshkataria/Code/service_center/db/migrate/20150625045117_create_ecol_unapproved_records.rb:3:in `change'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:606:in `exec_migration'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:820:in `up'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/migration.rb:798:in `migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/akhileshkataria/Code/service_center/vendor/bundle/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `foreign_keys' for #<ActiveRecord::ConnectionAdapters::OracleEnhanced::TableDefinition:0x007fcb9b534670>
```

**Comment by yahonda** [comment]
Please update Rails version to 4.2.1 or higher.

**Comment by yahonda** [comment]
The reason why I suggested to update Rails version to 4.2.1 or higher is that  https://github.com/rails/rails/commit/0230ad686118b60e89ef8cd2f7b2936099de6deb has been introduced into Rails 4.2.1 as a new feature.

https://github.com/rails/rails/blob/v4.2.1/activerecord/CHANGELOG.md
```ruby
Add a :foreign_key option to references and associated migration methods. The model and migration generators now use this option, rather than the add_foreign_key form.

Sean Griffin
```

What I can suggest you to use the newer version of Rails. If you still reproduces this after upgrading rails to 4.2.1 or newer version of Rails.
