### PR TITLE
Missing c-tor invocation

### PR DESCRIPTION
**Pull request by gavvvr**
Fix `NoMethodError: undefined method `ArgumentError' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:>`

### CODE REVIEW

**Review by koic — APPROVED** [review]
Nice! This looks good to me.

@yahonda This is a regression by #1669. I think it's worth backporting to release60 branch. What do you think about that?

**Comment by yahonda** [comment]
Thanks for the review. I'd need some specs to avoid future regressions.

**Comment by yahonda** [comment]
I mean I'm happy to backport this change to release60 branch with specs.

**Comment by yahonda** [comment]
Nevermind. Merging this pull request.
