### ISSUE TITLE
undefined local variable or method `sql' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x3ac701ca>

### ISSUE THREAD

**Issue by jlahtinen** [rsim/oracle-enhanced#1932]
https://github.com/rsim/oracle-enhanced/blob/1384ca03088f46f751423c5c5360c335c074e852/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb#L259

**Comment by jlahtinen** [comment]
script: https://gist.github.com/jlahtinen/1c71cb2dccc66fd57e4941d45202b4da

**Comment by jlahtinen** [comment]
possible fix: https://gist.github.com/jlahtinen/6cd243415d41ea2ba9b8d7031f3312a8

**Comment by jlahtinen** [comment]
I could make a PR also if really needed. Current master is hard for me to get tests pass although so I prefer not :roll_eyes:

**Comment by koic** [comment]
This error seems to be caused by #1546. Rails 5.2 and 6.0 has been targeted.
@yahonda Will it be backported to 5.2 and 6.0 branches when the master will be fixed?

**Comment by yahonda** [comment]
Thanks for the investigation. 
Actually, it depends how much change is necessary to address this issue to back port or not. 

Basically, I prefer to just back port to the latest release version because Oracle enhanced adapter 5.2.0 was released last year and this is the first issue reported after Oracle enhanced adapter 6.0.0 is out.

**Comment by koic** [comment]
Thanks for your reply.
In fact, I'm using Oracle enhanced adapter 1.8 with Rails 5.1.
I'm glad to have a migration path to Rails 6.0 if backported to Oracle enhanced adapter 5.2 stable branch. The problem is clear and its correction is simple.

**Comment by yahonda** [comment]
Understood and agreed. please go-ahead to open a pull request to master and backport it to release60 and release52 branches.

**Comment by koic** [comment]
I will take this issue later.

**Comment by yahonda** [comment]
Thanks for the update.
