### ISSUE TITLE
OracleEnhancedAdapter using offset and limit should return the records starting from offset n with offset(n) fails

### ISSUE THREAD

**Issue by yahonda** [rsim/oracle-enhanced#2158]
Following up #2157

### Steps to reproduce
Refer CI failure at https://travis-ci.com/github/rsim/oracle-enhanced/jobs/494935830

### Expected behavior
It should pass.

### Actual behavior
```ruby
  1) OracleEnhancedAdapter using offset and limit should return the records starting from offset n with offset(n)
495     Failure/Error:
496       collector << ") raw_sql_
497           WHERE rownum <= #{offset.expr.to_i + limit}
498     
499     NoMethodError:
500       undefined method `to_i' for #<ActiveModel::Attribute::WithCastValue:0x000055aa1911c5b0 @name="OFFSET", @value_before_type_cast=0, @type=#<ActiveModel::Type::Value:0x000055aa18e92f60 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil>
501       Did you mean?  to_s
```
### System configuration
**Rails version**:main branch

**Oracle enhanced adapter version**: 

**Ruby version**: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
271

**Oracle Database version**: Oracle Database 11g R2. It does not reproduce with Oracle Database 12c or higher.

**Comment by yahonda** [comment]
This behavior change has been introduced by https://github.com/rails/rails/pull/41577

Before this change `offset.expr` is a `Arel::Nodes::BindParam`, then it satisfies the condition below.

https://github.com/rsim/oracle-enhanced/blob/218161a9c593bac7c1beeb5d6ac89ac1afdd007d/lib/arel/visitors/oracle.rb#L31

After this change, `offset.expr` is a `ActiveModel::Attribute::WithCastValue` then the condition is not satisified. 

* before this change

```ruby
$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:404
==> Loading config from ENV or use default
==> Running specs with ruby version 2.7.2
==> Effective ActiveRecord version 7.0.0.alpha
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[404]}}

From: /home/yahonda/src/github.com/rsim/oracle-enhanced/lib/arel/visitors/oracle.rb @ line 31 :

    26:                   SELECT raw_sql_.*, rownum raw_rnum_
    27:                   FROM ("
    28:
    29:             collector = super(o, collector)
    30:
 => 31: binding.irb
    32:             if offset.expr.is_a? Nodes::BindParam
    33:               collector << ") raw_sql_ WHERE rownum <= ("
    34:               collector = visit offset.expr, collector
    35:               collector << " + "
    36:               collector = visit limit, collector

irb(#<Arel::Visitors::Oracle:0x00005580778e2d60>):001:0> offset
=> #<Arel::Nodes::Offset:0x0000558077be7e48 @expr=#<Arel::Nodes::BindParam:0x0000558077be7e70 @value=#<ActiveModel::Attribute::WithCastValue:0x0000558077be7e98 @name="OFFSET", @value_before_type_cast=0, @type=#<ActiveModel::Type::Value:0x0000558077e52188 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil>>>
irb(#<Arel::Visitors::Oracle:0x00005580778e2d60>):002:0> offset.class
=> Arel::Nodes::Offset
irb(#<Arel::Visitors::Oracle:0x00005580778e2d60>):003:0> offset.expr
=> #<Arel::Nodes::BindParam:0x0000558077be7e70 @value=#<ActiveModel::Attribute::WithCastValue:0x0000558077be7e98 @name="OFFSET", @value_before_type_cast=0, @type=#<ActiveModel::Type::Value:0x0000558077e52188 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil>>
irb(#<Arel::Visitors::Oracle:0x00005580778e2d60>):004:0> offset.expr.class
=> Arel::Nodes::BindParam
```

* after this change

```ruby
yahonda@myryzen:~/src/github.com/rsim/oracle-enhanced$ bundle exec rspec ./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb:404
==> Loading config from ENV or use default
==> Running specs with ruby version 2.7.2
==> Effective ActiveRecord version 7.0.0.alpha
Run options: include {:locations=>{"./spec/active_record/connection_adapters/oracle_enhanced_adapter_spec.rb"=>[404]}}

From: /home/yahonda/src/github.com/rsim/oracle-enhanced/lib/arel/visitors/oracle.rb @ line 31 :

    26:                   SELECT raw_sql_.*, rownum raw_rnum_
    27:                   FROM ("
    28:
    29:             collector = super(o, collector)
    30:
 => 31: binding.irb
    32:             if offset.expr.is_a? Nodes::BindParam
    33:               collector << ") raw_sql_ WHERE rownum <= ("
    34:               collector = visit offset.expr, collector
    35:               collector << " + "
    36:               collector = visit limit, collector

irb(#<Arel::Visitors::Oracle:0x000056059570ee28>):001:0> offset
=> #<Arel::Nodes::Offset:0x0000560595a1b648 @expr=#<ActiveModel::Attribute::WithCastValue:0x0000560595a1b670 @name="OFFSET", @value_before_type_cast=0, @type=#<ActiveModel::Type::Value:0x0000560595c818b0 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil>>
irb(#<Arel::Visitors::Oracle:0x000056059570ee28>):003:0> offset.class
=> Arel::Nodes::Offset
irb(#<Arel::Visitors::Oracle:0x000056059570ee28>):004:0> offset.expr
=> #<ActiveModel::Attribute::WithCastValue:0x0000560595a1b670 @name="OFFSET", @value_before_type_cast=0, @type=#<ActiveModel::Type::Value:0x0000560595c818b0 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil>
irb(#<Arel::Visitors::Oracle:0x000056059570ee28>):005:0> offset.expr.class
=> ActiveModel::Attribute::WithCastValue
irb(#<Arel::Visitors::Oracle:0x000056059570ee28>):006:0>
```
