### ISSUE TITLE
undefined method `type' for "NUMBER(11)":String 

### ISSUE THREAD

**Issue by lustremedia** [rsim/oracle-enhanced#622]
Just running into this issue, after upgrading from rails 4.1.10 to 4.2 latest
using:
oracle adaptor 1.5.6

I also see that there is a special 4.2 branch here, would that work better?

**Comment by lustremedia** [comment]
I also saw #536 but this ticket did not explain how to fix the issue.

**Comment by lustremedia** [comment]
Using:
gem 'activerecord-oracle_enhanced-adapter', github: 'rsim/oracle-enhanced', branch: 'rails42'

works, however upon install I got following error:

Fetching git://github.com/rsim/oracle-enhanced.git
remote: Counting objects: 5918, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 5918 (delta 9), reused 0 (delta 0), pack-reused 5893
Receiving objects: 100% (5918/5918), 4.23 MiB | 2.51 MiB/s, done.
Resolving deltas: 100% (2664/2664), done.
Fetching gem metadata from http://rubygems.org/.......Retrying dependency api due to error (2/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
.Retrying dependency api due to error (2/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
..Retrying dependency api due to error (2/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
Retrying dependency api due to error (3/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
.Retrying dependency api due to error (2/3): Bundler::MarshalError TypeError: incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
.
Fetching additional metadata from http://rubygems.org/..

**Comment by lustremedia** [comment]
What is the difference between branch42 and master?

**Comment by yahonda** [comment]
`rails42` was a topic branch to work for Rails 4.2. Now all changes at rails42 has been merged to master. rails42 branch will not be updated anymore.

Add this entry to your Gemfile and try to see if it still reproduces.
```ruby
gem "activerecord-oracle_enhanced-adapter", "~> 1.6.0.beta1" 
```

**Comment by yahonda** [comment]
Closing this. Please reopen if it still reproduce using the latest version of Oracle enhanced adapter 1.6.x.
