### PR TITLE
Fix an error when writing lobs

### LINKED ISSUE #1932: undefined local variable or method `sql' for #<ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter:0x3ac701ca>
https://github.com/rsim/oracle-enhanced/blob/1384ca03088f46f751423c5c5360c335c074e852/lib/active_record/connection_adapters/oracle_enhanced/database_statements.rb#L259

### PR DESCRIPTION
**Pull request by koic**
### Summary

Fixes #1932.

This PR fixes an error when writing lobs.
This error seems to be caused by #1546. Rails 5.2 and 6.0 has been targeted.

### Other Information

#1932 discusses backporting to Rails 5.2 and Rails 6.0.

### CODE REVIEW

**Comment by koic** [comment]
@yahonda If you are good about this PR, I'd like to backport this patch. Please tell me your planning when it's convenient for you.

**Comment by yahonda** [comment]
I have opened backport pull requests to release60 and release52 branch.
Let me release new versions of Oracle enhanced adapter like 6.0.1 and 5.2.7.
